### ISSUE TITLE
Python Counterexample Mapping

### ISSUE THREAD

**Issue by XAI360** [john-tornblom/VoTE#2]
Thanks for sharing the code. Would you please help me to understand how to obtain all possible counterexample mappings associated with an input sample with python binding?

**Comment by john-tornblom** [comment]
A counter-example of what, exactly? In any case, VoTE captures multiple inputs (precisely) in the interval domain, and whenever a prediction model violates some property, there are typically too many concrete values to enumerate. For example, in a simple one-dimensional input space where all inputs in the range [0, 1] violates a given property, there are 1,065,353,217 counter-examples to choose from (assuming 32bit floating point numbers). This number grows exponentially with respect to the number of inputs to the prediction function.

If you just need one counter example, you can extract that from within your property checker. Below is an example of a simple robustness property of a digit classifier, where the central point of violating input regions are printed to stdout.
```

import vote

from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

digits = load_digits()
rf = RandomForestClassifier(n_estimators=10)
rf.fit(digits.data, digits.target)

e = vote.Ensemble.from_sklearn(rf)
error_margin = 1
passed = 0

for xvec, label in zip(digits.data, digits.target):
    
    def check_robustness(m):
        o = vote.mapping_check_argmax(m, label)
        
        if o == vote.FAIL:
            center = [m.inputs[dim].lower + (m.inputs[dim].upper -
                                     m.inputs[dim].lower) / 2
                      for dim in range(m.nb_inputs)]

            assert(rf.predict([center]) != label)
            
            print('counter-example: f(%s) != %d' % (center, label))
            print('-' * 80)
            
        return o
    
    input_region = [(max(x - error_margin, 0), min(255, x + error_margin))
                    for x in xvec]
        
    if vote.PASS == e.absref(check_robustness, input_region):
        passed += 1
    

print('')
print('passed: %d/%d' % (passed, len(digits.data)))

```

I hope that helps!

**Comment by XAI360** [comment]
For a simple one dimensional input space, lets say x = 0.5 and error_margin = 0.1, Is there any way to make VoTE return counterexample ranges, for example, counterexamples lie within [0.4,0.46] and [0.55, 0.6] ? Sorry for more question

**Comment by john-tornblom** [comment]
Yes, ranges can be reported too. If you like to continue analyzing the remaining input space despite finding a violation, you can return vote.PASS instead of vote.FAIL, see example below.
```
import vote

from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

digits = load_digits()
rf = RandomForestClassifier(n_estimators=10)
rf.fit(digits.data, digits.target)

e = vote.Ensemble.from_sklearn(rf)
error_margin = 1

for xvec, label in zip(digits.data, digits.target):
    
    def check_robustness(m):
        o = vote.mapping_check_argmax(m, label)
        
        if o == vote.FAIL:
            conds = ['x%d ∈ %s' % (dim, [m.inputs[dim].lower, m.inputs[dim].upper])
                                   for dim in range(m.nb_inputs)]
            print(', '.join(conds))
            print('-' * 80)
            return vote.PASS
        
        return o
    
    input_region = [(max(x - error_margin, 0), min(255, x + error_margin))
                    for x in xvec]
    e.absref(check_robustness, input_region)
```

**Comment by XAI360** [comment]
The above example will exhaustively search for counterexample ranges right? Meaning it print out all the violate regions associated with each input sample?

**Comment by john-tornblom** [comment]
Yes, exactly

**Comment by XAI360** [comment]
Thanks for answer. Can the above code be configured to return combines disjoint robust regions and violate regions? for example, if x = 0.5 and error_margin = 0.1, can be as robust region (combines) = [0.44, 0.5] (left), [0.5, 0.55] (right) and violate region (combines) = [0.4, 0.4399] (left), [0.551, 0.6] (right)

The 2nd code print too many regions per sample, is there way to combine region like my example?

**Comment by john-tornblom** [comment]
I do not have an example of that, but I guess it is possible.

**Comment by XAI360** [comment]
Last request please. I would really appreciat. Can you please provide me with example code for combines disjoint robust and violate regions? Thank you .

**Comment by john-tornblom** [comment]
As I said, I do not have an example for that.

**Comment by XAI360** [comment]
Sorry for the additional question. In the second code example, where VoTE exhaustively searches for all counterexample regions, are those open or closed intervals? 

Also, it's not normal for the original test sample that was correctly identified (but not robust) to lie in the counterexample region, right? For example, if x = (0, 0, 0, 0) and my counterexample region, cr = (x0  ∈ [0,1], x1 ∈ [0,1], x2 ∈ [0, 1], x3 ∈ [0,1]), VoTE reports that the test sample x lies in the counterexample region cr, which should't be the case.

Am I missing something here? TIA
